import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";

const API = "https://web-production-801ec.up.railway.app";

function barWidth(value) {
  return `${Math.min(value, 100)}%`;
}

export default function ReportPage() {
  const { id } = useParams();
  const [report, setReport] = useState(undefined);
  const [error, setError] = useState("");

  useEffect(() => {
    async function loadReport() {
      try {
        const res = await fetch(`${API}/v1/reports/${id}`);
        const data = await res.json();
        const savedChain = localStorage.getItem("kryos_chain");

      if (report?.chain && savedChain && report.chain !== savedChain) {
        localStorage.removeItem("kryos_report_id");
        localStorage.removeItem("kryos_paid");

        window.location.href = "/";
        return;
      }

        if (!data) {
          setError("Report not found.");
          setReport(null);
          return;
        }

        setReport(data);
      } catch (err) {
        setError("Could not load report.");
        setReport(null);
      }
    }

    loadReport();
  }, [id]);

  if (report === undefined) {
    return <div style={{ padding: 24, color: "white" }}>Loading report...</div>;
  }

  if (error) {
    return <div style={{ padding: 24, color: "white" }}>{error}</div>;
  }

  const signals = report.analysis?.signals ?? {};

  const signalRows = [
    ["Circulating Ratio", signals.circulating_ratio],
    ["FDV Dilution", signals.fdv_dilution],
    ["TGE Unlock", signals.tge_unlock],
    ["Unlock Pressure", signals.unlock_pressure],
    ["Liquidity Support", signals.liquidity_support],
    ["Cliff Risk", signals.cliff_risk],
  ];

  return (
    <div style={{ padding: 24, color: "white" }}>
      <h1 style={{ fontSize: 28, marginBottom: 20 }}>Public Report</h1>
      <p style={{ opacity: 0.7 }}>
        Generated by Kryos Risk Engine v1
      </p>


      <div
        style={{
          background: "rgba(255,255,255,0.05)",
          padding: 20,
          borderRadius: 16,
          maxWidth: 820,
        }}
      >
        <h2 style={{ marginTop: 0 }}>
          {report.project.name} ({report.project.symbol})
        </h2>

        <p>Chain: {report.project.chain}</p>
        <p>Total Supply: {report.project.total_supply}</p>
        <p>FDV: {report.project.fdv}</p>
        <p>Circulating Supply: {report.project.circulating_supply}</p>
        <p>TGE Unlock: {report.project.tge_unlock}%</p>

        <h2 style={{ marginTop: 24 }}>Launch Score</h2>
        <p>Score: {report.analysis?.launch_score ?? "N/A"}/100</p>
        <p>Rating: {report.analysis?.rating ?? "N/A"}</p>

        <h3 style={{ marginTop: 20 }}>Key Risks</h3>
        {report.analysis?.risks?.length ? (
          <ul>
            {report.analysis.risks.map((r, i) => (
              <li key={i}>{r}</li>
            ))}
          </ul>
        ) : (
          <p>No major risks detected.</p>
        )}

        <h2 style={{ marginTop: 28 }}>Risk Signals</h2>
        <div style={{ display: "grid", gap: 14, marginTop: 12 }}>
          {signalRows.map(([name, signal]) => (
            <div
              key={name}
              style={{
                padding: 12,
                borderRadius: 12,
                background: "rgba(255,255,255,0.04)",
              }}
            >
              <div style={{ display: "flex", justifyContent: "space-between", marginBottom: 6 }}>
                <strong>{name}</strong>
                <span>{signal?.score ?? "N/A"}/100</span>
              </div>
              <div style={{ display: "flex", justifyContent: "space-between", marginBottom: 6 }}>
                <span>{signal?.label ?? "N/A"}</span>
                <span>{signal?.value ?? "—"}</span>
              </div>
              <div
                style={{
                  width: "100%",
                  height: 10,
                  borderRadius: 999,
                  background: "rgba(255,255,255,0.08)",
                  overflow: "hidden",
                }}
              >
                <div
                  style={{
                    width: barWidth(signal?.score ?? 0),
                    height: "100%",
                    borderRadius: 999,
                    background: "rgba(255,255,255,0.75)",
                  }}
                />
              </div>
            </div>
          ))}
        </div>

        <h2 style={{ marginTop: 28 }}>Unlock Pressure</h2>
        <p>
          Pressure Level: <strong>{report.unlock_pressure?.label ?? "N/A"}</strong>
        </p>

        <div style={{ display: "grid", gap: 12, marginTop: 12 }}>
          {(report.unlock_pressure?.months ?? []).map((item) => (
            <div key={item.month}>
              <div style={{ display: "flex", justifyContent: "space-between", marginBottom: 4 }}>
                <span>{item.month}</span>
                <span>{item.value}</span>
              </div>
              <div
                style={{
                  width: "100%",
                  height: 12,
                  borderRadius: 999,
                  background: "rgba(255,255,255,0.08)",
                  overflow: "hidden",
                }}
              >
                <div
                  style={{
                    width: `${Math.min(item.value * 3, 100)}%`,
                    height: "100%",
                    borderRadius: 999,
                    background: "rgba(255,255,255,0.75)",
                  }}
                />
              </div>
            </div>
          ))}
        </div>

        <p style={{ marginTop: 20 }}>Report ID: {report.id}</p>
      </div>
    </div>
  );
}
